### ISSUE TITLE
[QA] Device Problems are Displaying Incorrectly

### ISSUE THREAD

**Issue by jroodman** [vigetlabs/GroundRules#54]
Browser: Chrome
URL: GroundRules.co/devices

_Current:_
* When text is the only thing being displayed for a device problem, it is not vertically centered
* When an SVG is displayed for a device problem, it is not horizontally centered 
* When a device problem is opened, the underline for the device problem moves to below the device problem content

_Expected:_
* When text is the only thing being displayed for a device problem, it should be vertically centered
* When an SVG is displayed for a device problem, it should be horizontally centered
* When a device problem is opened, the underline for the device problem should stay directly underneath the device problem

**Comment by benjaminmodayil** [comment]
1. Vertically centered to what? There isn't anything here that you're saying it should be vertically centered with. According to what I see in the comp, it's right. Let me know otherwise, but I'm marking otherwise for now. Screenshots are definitely needed for these QA's I can't always be seeing what you're seeing.

2. I can understand this one. It's centered. When the animation takes place, parts of the animation will fill in that gap.

3. ✅

**Comment by jroodman** [comment]
Looking Good! There was a gray box there before also that wasn't in the comps, meant vertically centered to that, but looks awesome now without it.
